### ISSUE TITLE
whatsmyuseragent.org no longer shows user agent

### ISSUE THREAD

**Issue by merc1er** [AtuboDad/playwright_stealth#19]
It looks like the domain for the website http://whatsmyuseragent.org/ was not renewed and it now just shows ads.

It can be replaced by https://whatmyuseragent.com or others.

**Comment by AtuboDad** [comment]
> It looks like the domain for the website http://whatsmyuseragent.org/ was not renewed and it now just shows ads.
> 
> It can be replaced by https://whatmyuseragent.com or others.

yee!
